# ------------------------------------------------------------
# Build file for 32 bit ARM architectures
# ------------------------------------------------------------
FROM debian:stable AS build-armhf

# ------------------------------------------------------------
# Install dev packaged dependencies
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    build-essential \
    libavcodec-dev \
    libavdevice-dev \
    libavfilter-dev \
    libavformat-dev \
    libavutil-dev \
    libportaudio2 \
    libswresample-dev \
    libswscale-dev \
    pkg-config \
    python3-dev \
    libffi-dev \
    libjpeg-dev

# ------------------------------------------------------------
# Pull a separate base image for a clean final build
# ------------------------------------------------------------
FROM debian:stable AS final-armhf

# ------------------------------------------------------------
# Copy necessary libraries from the build image to the final image
# ------------------------------------------------------------
COPY --from=build-armhf /usr/lib/arm-linux-gnueabihf /usr/lib/arm-linux-gnueabihf

COPY --from=build-armhf /usr/include /usr/include

COPY --from=build-armhf /usr/lib /usr/lib

# ------------------------------------------------------------
# Install runtime dependencies
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    alsa-utils \
    bash \
    libportaudio2 \
    pkg-config \
    python3 \
    python3-pip \
    pipx

WORKDIR /app

# ------------------------------------------------------------
# Install sendspin
# ------------------------------------------------------------
RUN pipx install sendspin && \
    pipx ensurepath

ENV PATH="/root/.local/bin:${PATH}"

# ------------------------------------------------------------
# Setup entrypoint to call entrypoint.sh and run sendspin with passed arguments
# ------------------------------------------------------------
ENTRYPOINT ["/bin/sh", "-c", "$0 \"$@\"", "sendspin"]