FROM debian:stable

# ------------------------------------------------------------
# Install python dependencies
# ------------------------------------------------------------
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    pipx \
    libportaudio2

RUN pipx install sendspin && \
    pipx ensurepath

ENV PATH="/root/.local/bin:${PATH}"

ENTRYPOINT ["/bin/sh", "-c", "$0 \"$@\"", "sendspin"]